### ISSUE TITLE
set bugsnag releasestage

### ISSUE THREAD

**Issue by juliangruber** [segment-integrations/analytics.js-integration-bugsnag#2]
We need to set `data-releasestage` for our bugsnag. how would we best pass this information down to bugsnag?

**Comment by f2prateek** [comment]
Hmm I'm not entirely sure... what does this look like if you had a native integration with bugsnag?

**Comment by juliangruber** [comment]
We'd set the data-releasestage property on the script tag including bugsnag. There _might_ be a js api for this as well.

**Comment by f2prateek** [comment]
Ah I see - yeah they do have a JS API for it. https://cloudup.com/cXDRjHML2fu (https://bugsnag.com/docs/notifiers/js). We could add it as an option and just set it like the apiKey here https://github.com/segment-integrations/analytics.js-integration-bugsnag/blob/master/lib/index.js#L44.

**Comment by juliangruber** [comment]
that would be :egg:cellent!

**Comment by nblackburn** [comment]
You can do this directly with the following code...

``` javascript
 Bugsnag.releaseStage = 'production';
```
