### ISSUE TITLE
Identify enchancement

### ISSUE THREAD

**Issue by nblackburn** [segment-integrations/analytics.js-integration-bugsnag#3]
At the moment user information is passed to metaData but Bugsnag has a user object which would be a more fitting place for this information to be.

https://github.com/segment-integrations/analytics.js-integration-bugsnag/blob/master/lib/index.js#L76

**Comment by f2prateek** [comment]
Closed by #6

**Comment by nblackburn** [comment]
Do we have an ETA on when this will go live?
